### ISSUE TITLE
Nested Selects in obmmScript not working?

### ISSUE THREAD

**Issue by AnyOldName3** [erri120/OMOD-Framework#10]
**Describe the bug**
HGEC's installer has several selects of various forms - there's a `SelectWithDescription`, then a plain old `Select`, then, nested within that one, there's a `SelectWithPreviews`. The `SelectWithPreviews` isn't turned into a `DialogSelect` call, even though its predecessors are.

**You implementation**
I've tried this in the C# example, too, so it doesn't need my implementation.

**Expected behavior**
Each `Select*` call turns into a `DialogSelect` call.

**Versionlist**
Tested with https://github.com/erri120/OMOD-Framework/commit/4d0ba8a9a987cd5ef927d3be19fc4d7e9ce7b5d3 and .NET 4.7.2.

**Comment by erri120** [comment]
![15-10-2019 10-33-22 MProjectsOMOD-FrameworkOMOD-Framework-Example](https://user-images.githubusercontent.com/16577545/66814645-7909ec80-ef26-11e9-8d76-4872dc704cb2.png)
Changed the example a bit to include an actual implementation.

**Comment by AnyOldName3** [comment]
I've figured it out. It *is* a bug at your end, and the nesting is related, but the problem is with pipes. When you select the default option (i.e. the one with a pipe) the `Case` doesn't have the pipe (as it's a flag for OBMM to select that by default, not part of the option name), so you're falling out the `Select` without finding a match.

**Comment by AnyOldName3** [comment]
This is still closed, even though we agreed that it *was* actually a bug on Discord yesterday.

Here's the test file that I made that's clearly doing different things in OBMM and this framework. The extension's been changed because GitHub doesn't like `.omod` files. The script is here, too.
[new mod 1.0.zip](https://github.com/erri120/OMOD-Framework/files/3734690/new.mod.1.0.zip)

```
Select "This does different things in OBMM and OMOD_Framework", "|First Option", "Second Option",
	Case First Option
		Message "This is only shown in OBMM", "This is only shown in OBMM, and only when 'First Option' is selected"
		Break
	Case Second Option
		Message "This is shown in OBMM and OMOF-Framework", "This is shown in both obmmScript implementations, as long as 'Second Option' is selected"
		Break
EndSelect
```

Selecting the first option only works in OBMM, but selecting the second option works with either implementation.
