### ISSUE TITLE
No Release PDBs in Nuget package

### ISSUE THREAD

**Issue by AnyOldName3** [erri120/OMOD-Framework#11]
It's a pain getting C++/CLI working with .NET DLLs from other solution files, and if I'm using the Nuget version (which makes it a *little* easier) that makes my locally-built PDBs get rejected as incompatible. It would be easier if the guaranteed matching PDBs from your machine could be included in the next release.

**Comment by erri120** [comment]
9e7e5f5f60408c550d6b12d159a4e8f8694d2ae2
